<center>

# **CS353 ML Lab 9**

## Name: K V Sumanth Reddy
## Roll No: 181CO225
### Batch: Section 2
### Date: 06/04/2021
---
###Q: Implementation of Artificial Neural Network for **NOR Logic Gate** with 2-bit Binary Input.
---
</center>

###<b>Import Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from keras import models, layers, losses, optimizers, metrics

###<b>Making a Dataset

<center>

## Truth table for NOR gate

| A | B | A NOR B|
| -- | -- | -- |
| 0 | 0 | 1 |
| 0 | 1 | 0 |
| 1 | 0 | 0 |
| 1 | 1 | 0 |

</center>

In [3]:
x = np.random.randint(0,2,(10000,2))
y = x[:,0] + x[:,1]

for i in range(len(y)):
  if y[i]==0:
    y[i]=1
  else:
    y[i]=0

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size = 0.20, random_state = 0)

###<b>Neural Network

In [5]:
model = models.Sequential()
model.add(layers.Dense(1, input_shape=(2,), activation='sigmoid'))
model.compile(loss='mean_squared_error', optimizer='adam', 
              metrics=[metrics.categorical_accuracy])

In [6]:
result = model.fit(x_train, y_train, validation_split=(0.2), 
                   batch_size=100, epochs=40, verbose=1)

Epoch 1/40
64/64 [==============================] - 1s 9ms/step - loss: 0.2021 - categorical_accuracy: 1.0000 - val_loss: 0.1886 - val_categorical_accuracy: 1.0000
Epoch 2/40
64/64 [==============================] - 0s 2ms/step - loss: 0.1867 - categorical_accuracy: 1.0000 - val_loss: 0.1742 - val_categorical_accuracy: 1.0000
Epoch 3/40
64/64 [==============================] - 0s 2ms/step - loss: 0.1728 - categorical_accuracy: 1.0000 - val_loss: 0.1628 - val_categorical_accuracy: 1.0000
Epoch 4/40
64/64 [==============================] - 0s 2ms/step - loss: 0.1619 - categorical_accuracy: 1.0000 - val_loss: 0.1538 - val_categorical_accuracy: 1.0000
Epoch 5/40
64/64 [==============================] - 0s 2ms/step - loss: 0.1540 - categorical_accuracy: 1.0000 - val_loss: 0.1466 - val_categorical_accuracy: 1.0000
Epoch 6/40
64/64 [==============================] - 0s 2ms/step - loss: 0.1476 - categorical_accuracy: 1.0000 - val_loss: 0.1408 - val_categorical_accuracy: 1.0000
Epoch 7/40
64/64

In [7]:
output = model.evaluate(x_test,y_test)

63/63 [==============================] - 0s 1ms/step - loss: 0.0581 - categorical_accuracy: 1.0000


###<b>Predictions

In [8]:
y_pred=model.predict(x_test).round()

In [9]:
model.predict([[0,0]]).round()

array([[1.]], dtype=float32)

In [10]:
model.predict([[0,1]]).round()

array([[0.]], dtype=float32)

In [11]:
model.predict([[1,0]]).round()

array([[0.]], dtype=float32)

In [12]:
model.predict([[1,1]]).round()

array([[0.]], dtype=float32)

###<b>Results

**Accuracy**: 
$$\frac {TP+TN}{P+N}$$


**Precision**: $$\frac {TP}{TP+FP}$$

**Root Mean Squared Error**: $$\frac {TP}{TP+FN}$$

**F1 Score**: $$\frac {2TP}{2TP + FP+FN}$$

In [13]:
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: %f' % accuracy)

precision = precision_score(y_test, y_pred)
print('Precision: %f' % precision)

recall = recall_score(y_test, y_pred)
print('Recall: %f' % recall)

f1 = f1_score(y_test, y_pred)
print('F1 score: %f' % f1)

Accuracy: 1.000000
Precision: 1.000000
Recall: 1.000000
F1 score: 1.000000
